### ISSUE TITLE
Backend call failed: Operation not permitted

### ISSUE THREAD

**Issue by entailz** [GermainZ/xdg-desktop-portal-termfilechooser#13]
Hello! Firstly thanks for this I can't wait to use it. I'm getting this error from xdg-desktop-portal `Backend call failed: Operation not permitted` when I try to call the provided ranger script from termfilechooser. My window moves to the side as its trying to spawn something. Any idea what this might be?

**Comment by entailz** [comment]
solved.

**Comment by poperigby** [comment]
@entailz how did you fix this?

**Comment by poperigby** [comment]
Ah, figured it out. You have to make sure the script is executable.

**Comment by entailz** [comment]
> @entailz how did you fix this?

im an idiot and missed the `default_dir` in config 😔
